field: 905d4050-b5de-439e-9220-47dc22e79c95 # Blocks
fieldLayouts:
  022adb25-2943-4aaf-98d6-e1195bbf61a6:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: f87d1354-0d5f-4927-b6db-bcc62492451c # Exp Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: dd0ca978-c390-4fbb-92b6-ef4a5ddd506e
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 0a0c46fa-0854-4aa0-8861-c8d21ddea837 # Exp Intro Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ca53adc5-5242-44d1-ad07-beaf36ed2207
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 456f088a-e20c-4334-971c-cea80068ce1f # Exp Areas
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6d7f8307-f6e2-459b-a0cc-db229f5a9c67
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 26328ce4-e4b8-40be-9d6a-057194fb8581
        userCondition: null
fields:
  0a0c46fa-0854-4aa0-8861-c8d21ddea837: # Exp Intro Text
    columnSuffix: ngnmmysx
    contentColumnType: text
    fieldGroup: null
    handle: expIntroText
    instructions: null
    name: 'Exp Intro Text'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  456f088a-e20c-4334-971c-cea80068ce1f: # Exp Areas
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: expAreas
    instructions: null
    name: 'Exp Areas'
    searchable: false
    settings:
      blockTypeFields: 0
      changedFieldIndicator: 1890330635
      columns:
        __assoc__:
          -
            - f1d4b491-d0ba-4a7d-9e5c-9a0264175e65 # Exp Title
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - 21b7534d-7672-47ae-b26d-d5cb25cb3fdb # Exp Blurb
            -
              __assoc__:
                -
                  - width
                  - ''
      contentTable: '{{%stc_5_expareas}}'
      fieldLayout: row
      maxRows: 6
      minRows: null
      propagationKeyFormat: null
      propagationMethod: all
      selectionLabel: null
      staticField: null
    translationKeyFormat: null
    translationMethod: none
    type: verbb\supertable\fields\SuperTableField
  f87d1354-0d5f-4927-b6db-bcc62492451c: # Exp Title
    columnSuffix: ufrlsrwn
    contentColumnType: text
    fieldGroup: null
    handle: expTitle
    instructions: null
    name: 'Exp Title'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: expertise
name: Expertise
sortOrder: 5
