field: 905d4050-b5de-439e-9220-47dc22e79c95 # Blocks
fieldLayouts:
  7391b6c9-60e5-487c-bf89-6f7d478f62c4:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 4a016f61-52e8-44b0-a0c8-a4fe21cac3a7 # Gallery Grid Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8a17ff8f-ff9c-411f-840c-f6ad8c6e27ba
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 95419582-34ed-4c5e-bd17-c997a1e11481 # Gallery Grid
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 76609ffb-4930-451c-b546-882c939bc8e5
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: dcfb88a2-141f-41ea-8c2e-ae62d50d52b1
        userCondition: null
fields:
  4a016f61-52e8-44b0-a0c8-a4fe21cac3a7: # Gallery Grid Title
    columnSuffix: qtkumshe
    contentColumnType: text
    fieldGroup: null
    handle: galleryGridTitle
    instructions: null
    name: 'Gallery Grid Title'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  95419582-34ed-4c5e-bd17-c997a1e11481: # Gallery Grid
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: galleryGrid
    instructions: null
    name: 'Gallery Grid'
    searchable: false
    settings:
      blockTypeFields: 0
      changedFieldIndicator: 713820137
      columns:
        __assoc__:
          -
            - 2057d12d-f024-42e6-a095-7cfb013f1573 # Source
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - a901688a-56c4-451c-9ce9-0119b625e906 # Original
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - 3d3e84c7-10c2-412b-be32-bb2c69e7029e # Width
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - 7cc4ff04-eda1-416b-b056-3da3308cdad2 # Height
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - e29b52b2-6dae-444e-b61c-7a854e1fedad # Caption
            -
              __assoc__:
                -
                  - width
                  - ''
      contentTable: '{{%stc_8_gallerygrid}}'
      fieldLayout: matrix
      maxRows: null
      minRows: null
      propagationKeyFormat: null
      propagationMethod: all
      selectionLabel: null
      staticField: null
    translationKeyFormat: null
    translationMethod: none
    type: verbb\supertable\fields\SuperTableField
handle: gallerygrid
name: GalleryGrid
sortOrder: 7
