field: 905d4050-b5de-439e-9220-47dc22e79c95 # Blocks
fieldLayouts:
  234703e6-ac2b-4e44-88f0-db9a7fd08e4b:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 0800c23f-61f1-49e1-8997-a33cddbccfb4 # Slider Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 56be0105-c3a0-4e03-8064-05de505a4a3c
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 6851cca2-7fe4-4c10-86ef-7e29b349889a # Slider Stage
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 66ab0a57-e013-4132-88b2-2157f78e41bc
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 6b6e9c83-6d9a-4609-8c42-fd50e052d973
        userCondition: null
fields:
  0800c23f-61f1-49e1-8997-a33cddbccfb4: # Slider Title
    columnSuffix: shzmtbld
    contentColumnType: text
    fieldGroup: null
    handle: sliderTitle
    instructions: null
    name: 'Slider Title'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  6851cca2-7fe4-4c10-86ef-7e29b349889a: # Slider Stage
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: sliderStage
    instructions: null
    name: 'Slider Stage'
    searchable: false
    settings:
      blockTypeFields: 0
      changedFieldIndicator: 161113838
      columns:
        __assoc__:
          -
            - 28bdcc08-449a-4a6a-bd4f-01ac2a95fb7e # Text Sub
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - 757e0504-a513-4030-b764-0c463a175b67 # Text Heading
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - 2354f6f5-f4ab-4802-96f1-784de89e3bfc # Text Background
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - 61a7a5ad-a56a-4dcc-83ec-a291e5ef9360 # Slide Image
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - 130a5ec2-3d40-4467-a779-d8f0d5bdb283 # Slide Color
            -
              __assoc__:
                -
                  - width
                  - ''
      contentTable: '{{%stc_2_sliderstage}}'
      fieldLayout: matrix
      maxRows: null
      minRows: null
      propagationKeyFormat: null
      propagationMethod: all
      selectionLabel: null
      staticField: null
    translationKeyFormat: null
    translationMethod: none
    type: verbb\supertable\fields\SuperTableField
handle: imageSlider
name: 'Image Slider'
sortOrder: 2
