field: 905d4050-b5de-439e-9220-47dc22e79c95 # Blocks
fieldLayouts:
  273d3c8c-bb61-4d8f-b2f0-a9dba2f33d58:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 404b2348-f856-448a-b169-c0c5e2fa7952 # Quote Background Color
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 08573980-93ef-4ffc-a0a8-3489226eef12
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 0a2e93ad-4dc6-48c5-b91b-90ca0cf70c3e # Quote Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b9484db3-44c4-4294-9f8d-9010a92d8130
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 519d67e5-0dae-4f5d-9389-0dca3c56d3d4 # Quote Image Url
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: af556970-929f-4c6c-a0f9-444a7d4a7f6f
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 124ace79-506d-4549-b78b-844273b7e4c5 # Quoter
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 060d2956-ae1b-4461-ab3c-da39e246a917
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 259416a8-03ac-40e4-ab88-42487e4a6dc1 # Company
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 85f26c51-3112-42e0-88c4-2dac0a341993
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: bd88cdba-e6b4-4555-9817-81812c4e0406
        userCondition: null
fields:
  0a2e93ad-4dc6-48c5-b91b-90ca0cf70c3e: # Quote Title
    columnSuffix: gjcrvrjb
    contentColumnType: text
    fieldGroup: null
    handle: quoteTitle
    instructions: null
    name: 'Quote Title'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  124ace79-506d-4549-b78b-844273b7e4c5: # Quoter
    columnSuffix: hrfurani
    contentColumnType: text
    fieldGroup: null
    handle: quoter
    instructions: null
    name: Quoter
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  404b2348-f856-448a-b169-c0c5e2fa7952: # Quote Background Color
    columnSuffix: qwqxumgj
    contentColumnType: string
    fieldGroup: null
    handle: quoteBackgroundColor
    instructions: null
    name: 'Quote Background Color'
    searchable: false
    settings:
      options:
        -
          __assoc__:
            -
              - label
              - Red
            -
              - value
              - red
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Blue
            -
              - value
              - blue
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Indigo
            -
              - value
              - indigo
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  519d67e5-0dae-4f5d-9389-0dca3c56d3d4: # Quote Image Url
    columnSuffix: daqzizza
    contentColumnType: text
    fieldGroup: null
    handle: quoteImageUrl
    instructions: null
    name: 'Quote Image Url'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  259416a8-03ac-40e4-ab88-42487e4a6dc1: # Company
    columnSuffix: okspryun
    contentColumnType: text
    fieldGroup: null
    handle: company
    instructions: null
    name: Company
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: quote
name: Quote
sortOrder: 9
