field: 905d4050-b5de-439e-9220-47dc22e79c95 # Blocks
fieldLayouts:
  7c148a4f-86cb-44c9-a9db-824974c0a019:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 9f5d3acc-3237-459f-98fe-a2eacbf3cc6c # Testimonials Id
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9c8995e8-bc75-4be4-9f41-de412b5a8717
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: b3deab5e-7cc5-4c5f-aadd-f89cf0981ff5 # Testimonial Cards
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b6e7bf92-4216-4e98-b975-f8aeb357aed4
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: e4821516-cc17-4730-9b9d-58b51cb3b9c6
        userCondition: null
fields:
  9f5d3acc-3237-459f-98fe-a2eacbf3cc6c: # Testimonials Id
    columnSuffix: nmlpckvz
    contentColumnType: text
    fieldGroup: null
    handle: testimonialsId
    instructions: null
    name: 'Testimonials Id'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  b3deab5e-7cc5-4c5f-aadd-f89cf0981ff5: # Testimonial Cards
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: testimonialCards
    instructions: null
    name: 'Testimonial Cards'
    searchable: false
    settings:
      blockTypeFields: 0
      changedFieldIndicator: 962908277
      contentTable: '{{%stc_testimonialcards}}'
      fieldLayout: row
      maxRows: null
      minRows: null
      propagationKeyFormat: null
      propagationMethod: all
      selectionLabel: null
      staticField: null
    translationKeyFormat: null
    translationMethod: none
    type: verbb\supertable\fields\SuperTableField
handle: testimonialSlider
name: 'Testimonial Slider'
sortOrder: 11
