field: 905d4050-b5de-439e-9220-47dc22e79c95 # Blocks
fieldLayouts:
  24a0cd55-35aa-493d-bdc7-c95e95482ee2:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 3dddb480-1c0c-4edb-8279-89763aac765c # Text Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 54ef2d9d-f63f-4666-86ff-4671464f2446
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: dde2c168-95d6-497e-ac05-6e84f4ceb296
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 57c2ef51-4990-4ee2-9dfb-54893952a52e
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 67dfc232-2dd7-44bb-900b-28df01e555df # Text Content
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3e8c5fdd-9093-4fbb-aae4-c3fa32e7b03f
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 8185c4c8-1256-48d7-89b8-62f7b76b3868 # Display Border Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: cf49d811-d512-4796-aa05-759ec1e27312
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: bcd825b7-ef4d-4809-9fac-31054386d665 # Select Border Display
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4f975deb-800e-451a-96a4-416ad750dda6
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 7dbcc446-f734-469c-9c85-6b0f2b94d4b7
        userCondition: null
fields:
  3dddb480-1c0c-4edb-8279-89763aac765c: # Text Title
    columnSuffix: kpelgpvb
    contentColumnType: text
    fieldGroup: null
    handle: textTitle
    instructions: null
    name: 'Text Title'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  67dfc232-2dd7-44bb-900b-28df01e555df: # Text Content
    columnSuffix: jaemslbd
    contentColumnType: text
    fieldGroup: null
    handle: textContent
    instructions: null
    name: 'Text Content'
    searchable: false
    settings:
      availableTransforms: ''
      availableVolumes: ''
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: null
      purifyHtml: true
      redactorConfig: null
      removeEmptyTags: false
      removeInlineStyles: false
      removeNbsp: false
      showHtmlButtonForNonAdmins: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
  8185c4c8-1256-48d7-89b8-62f7b76b3868: # Display Border Image
    columnSuffix: ulumlghk
    contentColumnType: boolean
    fieldGroup: null
    handle: displayBorderImage
    instructions: null
    name: 'Display Border Image'
    searchable: false
    settings:
      default: false
      offLabel: Hide
      onLabel: Show
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Lightswitch
  bcd825b7-ef4d-4809-9fac-31054386d665: # Select Border Display
    columnSuffix: kkesixnw
    contentColumnType: string
    fieldGroup: null
    handle: selectBorderDisplay
    instructions: null
    name: 'Select Border Display'
    searchable: false
    settings:
      options:
        -
          __assoc__:
            -
              - label
              - Left
            -
              - value
              - left
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Right
            -
              - value
              - right
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Both
            -
              - value
              - both
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  dde2c168-95d6-497e-ac05-6e84f4ceb296:
    columnSuffix: nnukoivd
    contentColumnType: text
    fieldGroup: null
    handle: textBoldTitle
    instructions: null
    name: 'Text Bold Title'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: textBlock
name: 'Text Block'
sortOrder: 8
