fieldLayouts:
  1b2eca9a-401d-44cb-b760-21d616967b3f:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            uid: a246fa91-ae0b-4589-b0fb-3b5b26f4ea3e
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 3b1bed77-e300-4122-8f9d-815971f5766a
        userCondition: null
handle: sport
name: Sport
