fieldLayouts:
  c80abd98-ca76-4c21-90aa-4f01b3ea1e9e:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: d1129dd6-7980-4025-8863-8f27ab8722d3
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 82a05a0b-aa09-4d1a-b32b-183c733990fd # Article Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4bf88b0a-068d-482b-a01e-5a7b115435ea
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 7e55cefd-659d-4e10-b31d-4e0a68dad821 # Article Excerpt
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c903a215-8165-49af-af40-55c980cc520a
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: dcefe02c-84a8-42bc-aee9-221f9935c656 # Article Type
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a3b2c975-51cf-4906-86db-371889657502
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition:
              class: craft\elements\conditions\entries\EntryCondition
              conditionRules:
                -
                  class: craft\fields\conditions\OptionsFieldConditionRule
                  fieldUid: dcefe02c-84a8-42bc-aee9-221f9935c656 # Article Type
                  operator: in
                  uid: 9ed3506d-2d58-4027-8875-44f3e93b8bd6
                  values:
                    - text
              elementType: craft\elements\Entry
              fieldContext: global
            fieldUid: 2a1d967c-a824-49c2-a84f-727409a9265c # Article Image Url
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1961b7a2-1752-462c-8589-29dea925d87b
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition:
              class: craft\elements\conditions\entries\EntryCondition
              conditionRules:
                -
                  class: craft\fields\conditions\OptionsFieldConditionRule
                  fieldUid: dcefe02c-84a8-42bc-aee9-221f9935c656 # Article Type
                  operator: in
                  uid: 85e9f54a-95ea-4444-b2df-4d2d39ab88b1
                  values:
                    - text
              elementType: craft\elements\Entry
              fieldContext: global
            fieldUid: dd43e7fb-8a8d-4e4a-80dd-55343718f638 # Article Image Alt
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 84492bc7-b01c-4c0a-ba67-258824a7f727
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition:
              class: craft\elements\conditions\entries\EntryCondition
              conditionRules:
                -
                  class: craft\fields\conditions\OptionsFieldConditionRule
                  fieldUid: dcefe02c-84a8-42bc-aee9-221f9935c656 # Article Type
                  operator: in
                  uid: 851de778-bbd5-4e97-963c-de6430fdf5a1
                  values:
                    - video
              elementType: craft\elements\Entry
              fieldContext: global
            fieldUid: 14a89346-2314-4eeb-9ef0-25a60001b329 # Article Video Embed
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f9f72e9a-2edc-4fc0-9959-b8073e0f6867
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 66e654c6-de20-49fb-928c-0e804ee78725 # Article Content
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c723901d-0d11-44dd-a447-b93eb229828d
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 04d54980-b674-4adf-8863-e247f35d1235 # Related Articles
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 89327543-deec-4ef7-8e36-d4805df95920
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 0b139721-a101-4a49-a3ed-59fd1da602aa
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 152ed4dc-c4b0-4a18-af15-2537400eef62 # Meta Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 76456f4b-4e63-46ae-8e1f-8d4f415a6282
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 7dd70b17-9357-4d42-9682-f30ace3ca653 # Meta Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1643579f-1a01-41d4-a60b-0445f18781ca
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 9582ff3f-3e0e-43b4-881b-74219a1782d1 # Meta Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d88ef4f0-0177-4917-a0ec-7c437156619c
            userCondition: null
            warning: null
            width: 100
        name: Meta
        uid: 117232f8-8ef7-45f7-8e21-9e0c38007522
        userCondition: null
handle: articles
hasTitleField: true
name: Articles
section: b5af17cf-b5f1-4fef-bd1f-770763583356 # Articles
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
