fieldLayouts:
  c80abd98-ca76-4c21-90aa-4f01b3ea1e9e:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: d1129dd6-7980-4025-8863-8f27ab8722d3
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 3b79fdc0-5724-4d9b-a5e9-380151a05b21 # Home Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b25d64a4-1117-4c88-8283-750b66c53b0a
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 0b139721-a101-4a49-a3ed-59fd1da602aa
        userCondition: null
handle: articles
hasTitleField: true
name: Articles
section: b5af17cf-b5f1-4fef-bd1f-770763583356 # Articles
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
