fieldLayouts:
  032bb257-f1d1-45cb-9518-42ac34f69661:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 7ee2c343-6b68-49ca-a27c-df130b8e677d
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 3b79fdc0-5724-4d9b-a5e9-380151a05b21 # Home Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8eeb265b-c0aa-406f-a102-b6504f26941e
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition:
              class: craft\elements\conditions\entries\EntryCondition
              conditionRules:
                -
                  class: craft\fields\conditions\TextFieldConditionRule
                  fieldUid: 3b79fdc0-5724-4d9b-a5e9-380151a05b21 # Home Title
                  operator: notempty
                  uid: 4e940f0c-9e9a-4f12-b656-dac244de7aa7
                  value: ''
              elementType: craft\elements\Entry
              fieldContext: global
            fieldUid: bfbacae8-4a0c-46a1-bd97-6bacaabf223d # Home Sub Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0f1f238f-06fe-491e-8bd4-4fe6cd1ba874
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 4cec6b05-014b-4e78-b472-830064d3db85
        userCondition: null
handle: homepage
hasTitleField: false
name: Homepage
section: dff2967f-e66b-48bb-b2c7-1303aa109beb # Homepage
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
