fieldLayouts:
  f7b53d7a-04bc-4047-9ce5-c71bf6e9ce23:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 2bfff517-b8ad-47de-b73a-dba0d44d166a
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: f4a4e19f-3c33-433b-9a94-08def95be97c # Studio Eyebrow Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 27514f0d-69bc-4485-ac9c-db47ec444b6a
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 31526c47-31c5-4606-9ad4-516804fb1e2f # Studio Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 21186810-8842-433b-a3e2-2c49438f7018
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 378fe6e9-2e49-4fa3-b100-bee4a5e9c3f3 # Studio Intro
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0070226c-59cb-4933-81dd-3bef8a38eae6
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 67c82c49-0b67-430e-9fcf-d86ec6a52116 # Studio CTA
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 90accaea-387d-4553-99cf-0c0f4d08f11a
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: ad575b29-c9e7-42ca-b2fa-894a02318574 # Studio More About
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1fe4e58f-44ae-48c0-a470-65ddcd85ec59
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 01dccff3-01ad-4244-86f8-bc11b79456fd # Studio More About Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6e5a6bdc-58bb-4740-a8db-f232455f1e69
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: b51d2e69-9761-4dd2-8518-83aad61fe142 # Studio Industry Exp Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 16eb8827-cbf1-494d-9fae-a24eae078e63
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 458df070-681a-4f31-a897-a60b7133f40e # Studio Industry Exp Intro
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c8c3ce2c-cb0e-4dd8-bf2e-4b070ae8e833
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 615561c0-3497-403a-9570-c597264c195f # Studio Industry Exp Panels
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fbb7d040-d782-46c7-8c11-def9b189cc16
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 3582a8f1-e1be-4c1c-b1d9-6190e9aa0aa1
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 152ed4dc-c4b0-4a18-af15-2537400eef62 # Meta Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c26f15c5-7aa0-432c-ac8a-cc3ea99a307c
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 7dd70b17-9357-4d42-9682-f30ace3ca653 # Meta Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f99ecbf7-46eb-46d7-96ef-6c9f19ba8f51
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 9582ff3f-3e0e-43b4-881b-74219a1782d1 # Meta Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b0d41f00-e883-436c-a24f-edfdddc1aa28
            userCondition: null
            warning: null
            width: 100
        name: Meta
        uid: ae3723fb-c0bb-4d54-9885-6e61458b8dfe
        userCondition: null
handle: studio
hasTitleField: false
name: Studio
section: ca982994-80f8-4a96-a3df-96f3cb0f33cb # Studio
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
