defaultPlacement: end
fieldLayouts:
  4f4ef8a7-bd53-4cad-8c09-8e85d991cd97:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            uid: ec34179a-7f4a-42a4-8eba-68bff6bd321c
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 2c4b341f-5397-448f-a91e-fd6a20fdc7ba
        userCondition: null
handle: webDev
name: 'Web Dev'
siteSettings:
  99385565-aceb-43e6-8be5-09e9913c7123: # blpcraft
    hasUrls: true
    template: null
    uriFormat: 'web-dev/{slug}'
structure:
  maxLevels: null
  uid: 7e1a339f-3d1e-49c3-bd2d-778ed630f3c1
