columnSuffix: null
contentColumnType: string
fieldGroup: a83c69d1-da9d-4df2-add8-f8261d91be86 # Articles
handle: articleCategory
instructions: null
name: 'Article Category'
searchable: false
settings:
  allowLimit: false
  allowMultipleSources: false
  allowSelfRelations: false
  branchLimit: null
  localizeRelations: false
  maxRelations: null
  minRelations: null
  selectionLabel: null
  showSiteMenu: false
  source: 'group:41aff8b9-a23e-4bf1-aa6c-e890d3e02ae2' # Tech
  sources: '*'
  targetSiteId: null
  validateRelatedElements: false
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Categories
