changedFieldIndicator: 46408549
field: 95419582-34ed-4c5e-bd17-c997a1e11481 # Gallery Grid
fieldLayouts:
  7e12ead1-30dc-4bb8-8884-a73c35bb1ea3:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 2057d12d-f024-42e6-a095-7cfb013f1573 # Source
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d96370a9-dc0e-4cd9-bbac-3159e6c0bc80
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: a901688a-56c4-451c-9ce9-0119b625e906 # Original
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 03636d33-9934-464a-83be-73a0f6b6069d
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 3d3e84c7-10c2-412b-be32-bb2c69e7029e # Width
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ffcc7654-2f01-444d-84ca-9132de12c006
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 7cc4ff04-eda1-416b-b056-3da3308cdad2 # Height
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: efd80375-3026-4a1a-8dd7-1cd1bda5b51a
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: e29b52b2-6dae-444e-b61c-7a854e1fedad # Caption
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8c83079e-3587-415b-9d21-0d85328b3150
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 970e89c1-60bc-45d8-8f62-f4bd48229615
        userCondition: null
fields:
  3d3e84c7-10c2-412b-be32-bb2c69e7029e: # Width
    columnSuffix: tkuvdhbg
    contentColumnType: text
    fieldGroup: null
    handle: width
    instructions: null
    name: Width
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  7cc4ff04-eda1-416b-b056-3da3308cdad2: # Height
    columnSuffix: ngfguksr
    contentColumnType: text
    fieldGroup: null
    handle: height
    instructions: null
    name: Height
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  2057d12d-f024-42e6-a095-7cfb013f1573: # Source
    columnSuffix: auruhyep
    contentColumnType: text
    fieldGroup: null
    handle: src
    instructions: null
    name: Source
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  a901688a-56c4-451c-9ce9-0119b625e906: # Original
    columnSuffix: wwasxtth
    contentColumnType: text
    fieldGroup: null
    handle: original
    instructions: null
    name: Original
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  e29b52b2-6dae-444e-b61c-7a854e1fedad: # Caption
    columnSuffix: kiggrayr
    contentColumnType: text
    fieldGroup: null
    handle: caption
    instructions: null
    name: Caption
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
