changedFieldIndicator: null
field: b3deab5e-7cc5-4c5f-aadd-f89cf0981ff5 # Testimonial Cards
fieldLayouts:
  35aadded-c13b-43a5-9329-5979741b2c13:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: c92d57de-10e9-49c9-95fd-3ce5a9d78ecb # Testimonial
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4a6f1222-dd3d-4f07-a174-208ca9814b55
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: c5458553-2173-4d34-8c44-a2460fa0f755 # Testimonial Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8b391bc2-2213-4c53-8508-5164b7a0b9ec
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: f99f15b0-c7dc-4388-bfc1-177955296c97 # Testimonial Client
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 709bcc29-6bfb-4b7a-bca3-a1f7904c23e5
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 8f689d0b-e5f9-4adf-b837-168192814485
        userCondition: null
fields:
  c92d57de-10e9-49c9-95fd-3ce5a9d78ecb: # Testimonial
    columnSuffix: tnwclgjg
    contentColumnType: text
    fieldGroup: null
    handle: testimonial
    instructions: null
    name: Testimonial
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  c5458553-2173-4d34-8c44-a2460fa0f755: # Testimonial Image
    columnSuffix: ajlwvfzv
    contentColumnType: text
    fieldGroup: null
    handle: testimonialImage
    instructions: null
    name: 'Testimonial Image'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  f99f15b0-c7dc-4388-bfc1-177955296c97: # Testimonial Client
    columnSuffix: fziqbidk
    contentColumnType: text
    fieldGroup: null
    handle: testimonialClient
    instructions: null
    name: 'Testimonial Client'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
