changedFieldIndicator: null
field: 4a745322-2056-4598-8d22-d45429b4da4f # Home Slider Matrix
fieldLayouts:
  7ac3940a-d4a0-47bf-86de-a2953180b9c1:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: cbecaf62-cf2e-4f09-b7e1-172602f1dc5c # Text Sub
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: dd1ab0e5-f1f9-4696-81cd-9e000f4d9998
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: d5111eb7-7238-465f-8c95-5e0faa1361d3 # Text Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1cc88422-cad7-478f-846e-df39baf457c6
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 1f97f6d1-86f0-4c9a-aac9-13c5f2ecc30a # Text Background
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 072b6c0b-4bb2-4950-9a6a-fb33f4761df7
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 1cbdb7f4-470b-4fe3-8755-2c7cd9052403 # Slide Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 176081d9-6409-488f-bf27-8bfeb4b495ef
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 66423ff9-39a2-4ae0-ba45-f6460d7a2408 # Slide Color
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d833c9ab-f596-4c7d-9428-d250406f7f88
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 4ba9b626-fc30-4a99-a410-f2b233e936c3
        userCondition: null
fields:
  1cbdb7f4-470b-4fe3-8755-2c7cd9052403: # Slide Image
    columnSuffix: yqcrzgnd
    contentColumnType: text
    fieldGroup: null
    handle: slideImage
    instructions: null
    name: 'Slide Image'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  1f97f6d1-86f0-4c9a-aac9-13c5f2ecc30a: # Text Background
    columnSuffix: ovwqkeoj
    contentColumnType: text
    fieldGroup: null
    handle: textBackground
    instructions: null
    name: 'Text Background'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  66423ff9-39a2-4ae0-ba45-f6460d7a2408: # Slide Color
    columnSuffix: mkdlqwef
    contentColumnType: string
    fieldGroup: null
    handle: slideColor
    instructions: null
    name: 'Slide Color'
    searchable: false
    settings:
      options:
        -
          __assoc__:
            -
              - label
              - Blue
            -
              - value
              - blue
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Yellow
            -
              - value
              - yellow
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Red
            -
              - value
              - red
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Gray
            -
              - value
              - gray
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'Dark Gray'
            -
              - value
              - dark-gray
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  cbecaf62-cf2e-4f09-b7e1-172602f1dc5c: # Text Sub
    columnSuffix: udwjynyr
    contentColumnType: text
    fieldGroup: null
    handle: textSub
    instructions: null
    name: 'Text Sub'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  d5111eb7-7238-465f-8c95-5e0faa1361d3: # Text Heading
    columnSuffix: umrxogxz
    contentColumnType: text
    fieldGroup: null
    handle: textHeading
    instructions: null
    name: 'Text Heading'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
