defaultPlacement: end
enableVersioning: true
handle: contact
name: Contact
previewTargets:
  -
    __assoc__:
      -
        - label
        - Local
      -
        - urlFormat
        - 'http://localhost:3000/api/preview?token=WxQXrQAuWGI1LvhIKpXjSGESi8ff8NcjjmMNiQZVB7H6pml6uRVNcoCL0ZQEcwQv&canonicalId&slug={slug}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  99385565-aceb-43e6-8be5-09e9913c7123: # blpcraft
    enabledByDefault: true
    hasUrls: true
    template: contact/_entry
    uriFormat: contact
type: single
