defaultPlacement: end
enableVersioning: true
handle: homepage
name: Homepage
previewTargets:
  -
    __assoc__:
      -
        - label
        - Local
      -
        - urlFormat
        - 'http://localhost:3000/api/preview?token=WxQXrQAuWGI1LvhIKpXjSGESi8ff8NcjjmMNiQZVB7H6pml6uRVNcoCL0ZQEcwQv&canonicalId&slug={''/''}'
      -
        - refresh
        - '1'
  -
    __assoc__:
      -
        - label
        - Production
      -
        - urlFormat
        - 'http://busylittlepixels.com/api/preview?token=WxQXrQAuWGI1LvhIKpXjSGESi8ff8NcjjmMNiQZVB7H6pml6uRVNcoCL0ZQEcwQv&canonicalId&slug={''/''}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  99385565-aceb-43e6-8be5-09e9913c7123: # blpcraft
    enabledByDefault: true
    hasUrls: true
    template: homepage/_entry
    uriFormat: __home__
type: single
