defaultPlacement: end
enableVersioning: true
handle: studio
name: Studio
previewTargets:
  -
    __assoc__:
      -
        - label
        - Local
      -
        - urlFormat
        - 'http://localhost:3000/api/preview?token=nLMYzdELRP22DvJk86ADfGytdveGkuBR&canonicalId&uri={slug}'
      -
        - refresh
        - '1'
  -
    __assoc__:
      -
        - label
        - Production
      -
        - urlFormat
        - 'https://busylittlepixels.com/api/preview?token=nLMYzdELRP22DvJk86ADfGytdveGkuBR&canonicalId&uri={slug}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  99385565-aceb-43e6-8be5-09e9913c7123: # blpcraft
    enabledByDefault: true
    hasUrls: true
    template: studio/_entry
    uriFormat: studio
type: single
